package xyz.wingio.dimett.utils

import android.content.Context
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.json.Json
import org.koin.core.component.KoinComponent
import org.koin.core.component.inject
import java.util.regex.Pattern

/**
 * Collection of utilities for dealing with emojis
 */
object EmojiUtils : KoinComponent {

    private val context: Context by inject()
    private val json: Json by inject()

    /**
     * Parses `assets/emoji.json` and returns a map of emoji codepoints to the Twemoji versions resource name located in `res/raw`
     */
    val emojis by lazy {
        val _json = String(context.assets.open("emoji.json").readBytes())
        json.decodeFromString<EmojiJson>(_json).emoji
    }

    /**
     * An autogenerated regex pattern matching every supported emoji
     *
     * @see [xyz.wingio.dimett.ast.addUnicodeEmojiRule]
     */
    val regex by lazy {
        "^(${
            emojis.keys.sortedByDescending { it.length }.joinToString("|") { emoji ->
                Pattern.quote(emoji)
            }
        })"
    }

}

/**
 * Usable representation of `assets/emoji.json`
 */
@Serializable
data class EmojiJson(
    val emoji: Map<String, String>
)