name: Build debug APK

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - '.idea/*'
      - 'LICENSE'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - '.idea/*'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build APK
        run: chmod +x ./gradlew && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Dimett
          path: app/build/outputs/apk/debug/app-debug.apk